# Generated by Django 4.2.27 on 2025-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='price_per_night',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
