# Generated by Django 4.2.27 on 2025-12-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(db_index=True)),
                ('date_end', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.hotelroom')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', 'date_start', 'date_end'], name='idx_booking_room_dates')],
            },
        ),
    ]
