# Generated by Django 4.2.27 on 2025-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_end',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_start',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'date_start', 'date_end'], name='idx_booking_room_dates'),
        ),
    ]
